name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: See env
        run: |
          env

      - name: Wait a bit
        run: |
          sleep 30
